FROM python:3.10-slim
RUN apt-get update && apt-get install -y git libgomp1 && rm -rf /var/lib/apt/lists/*
# Cài đặt tất cả thư viện nặng ở đây để lưu vào cache của Base Image
RUN pip install --no-cache-dir \
    fastapi uvicorn mlflow dagshub pandas scikit-learn \
    pika pymongo lightgbm transformers torch psutil requests joblib numpy
