# Finalized Trainer Image
FROM registry.ntdevopsregistry.io.vn/mlops/sentiment-base:latest

WORKDIR /app

# Vì thư viện đã có sẵn trong Base Image, ta chỉ cần copy code vào nếu cần
# Hoặc giữ nguyên để Airflow tự clone code qua InitContainer
CMD ["python", "train.py"]
