FROM python:3.10-slim

WORKDIR /app

# Cài đặt git (để InitContainer dùng clone code)
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Cài đặt thư viện ML cốt lõi và các thư viện cần cho AWS/MLflow
RUN pip install --no-cache-dir \
    pandas \
    scikit-learn \
    mlflow \
    python-dotenv \
    boto3 \
    pymysql \
    requests \
    pymongo

# Pod sẽ tự kéo code vào thư mục này lúc chạy, nên không cần COPY code
CMD ["python", "train.py"]
