version: '3.8'

services:
  # --- 3. MONGODB ---
  mongodb:
    image: mongo:latest
    container_name: spotify_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  # --- 4. LABEL STUDIO ---
  label-studio:
    image: heartexlabs/label-studio:latest
    container_name: spotify_label_studio
    ports:
      - "8086:8080"
    volumes:
      - label_data:/label-studio/data

# --- KHAI BÁO NAMED VOLUMES ĐỂ DOCKER TỰ QUẢN LÝ ---
volumes:
  db_data:
  mongo_data:
  label_data:
