# custom-values.yaml

# 1. Dùng KubernetesExecutor để gọi K8s (Docker Desktop) đẻ Pod tự động
executor: "KubernetesExecutor"

# 2. Tắt các thành phần nặng không cần thiết
redis:
  enabled: false
flower:
  enabled: false
workers:
  replicas: 0 # Không cần worker chạy ngầm vì đã dùng K8s Executor

# 3. Tạo sẵn tài khoản đăng nhập (khỏi phải tìm mật khẩu)
webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: admin
    password: admin
