apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  namespace: mlops-sentiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
  template:
    metadata:
      labels:
        app: collector
    spec:
      imagePullSecrets:
        - name: harbor-secret
      containers:
      - name: collector
        image: registry.ntdevopsregistry.io.vn/mlops/collector:2f88a83e8ebd00f884f9a8d80276641f8634fdca
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT_VAL
          value: "6379"
---
apiVersion: v1
kind: Service
metadata:
  name: collector
  namespace: mlops-sentiment
spec:
  selector:
    app: collector
  ports:
  - port: 8002
    targetPort: 8000
