apiVersion: apps/v1
kind: Deployment
metadata:
  name: evidently-monitoring
  namespace: mlops-sentiment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: evidently-monitoring
  template:
    metadata:
      labels:
        app: evidently-monitoring
    spec:
      containers:
      - name: monitoring
        image: phanphan1504/spotify-monitoring:v10
        env:
        - name: RABBITMQ_HOST
          value: "rabbitmq-service.mlops-sentiment.svc.cluster.local" # Dùng FQDN luôn cho chắc ăn nha!
        - name: EVIDENTLY_URL
          # CẬP NHẬT CỔNG THÀNH 8000:
          value: "http://evidently-service.mlops-sentiment.svc.cluster.local:8000"
