apiVersion: v1
kind: Pod
metadata:
  name: manual-train-test
  namespace: airflow
spec:
  imagePullSecrets:
  - name: harbor-secret
  initContainers:
  - name: git-pull-only
    image: registry.ntdevopsregistry.online/mlops/sentiment-trainer:latest
    imagePullPolicy: IfNotPresent
    command: ["/bin/sh", "-c"]
    args:
      - |
        echo "🚀 Cloning Source Code from GitHub..."
        # Kéo code mới nhất về ổ cứng dùng chung
        git clone https://davidmoi2135:${GITHUB_TOKEN}@github.com/davidmoi2135/Spotify-Sentiment-MLOps.git /opt/repo
        echo "✅ Code pulled successfully!"
    env:
    - name: GITHUB_TOKEN
      valueFrom: { secretKeyRef: { name: train-secrets, key: GITHUB_TOKEN } }
    volumeMounts:
    - name: shared-code
      mountPath: /opt/repo

  containers:
  - name: train-container
    image: registry.ntdevopsregistry.online/mlops/sentiment-trainer:latest
    imagePullPolicy: IfNotPresent
    workingDir: /opt/repo/model
    command: ["python", "train.py"]
    env:
    - name: DAGSHUB_USERNAME
      value: "davidmoi2135"
    - name: DAGSHUB_TOKEN
      valueFrom:
        secretKeyRef:
          name: train-secrets
          key: DAGSHUB_TOKEN
    volumeMounts:
    - name: shared-code
      mountPath: /opt/repo

  volumes:
  - name: shared-code
    emptyDir: {}

  restartPolicy: Never
