apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spotify-sentiment-mlops
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/davidmoi2135/Spotify-Sentiment-MLOps.git
    targetRevision: deploy  # ArgoCD sẽ theo dõi nhánh này
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-sentiment
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
