name: Manual Build and Push Model Service

on:
  # Cú pháp này cho phép bạn vào tab Actions trên GitHub để bấm nút "Run workflow" bằng tay
  workflow_dispatch: 
    inputs:
      version_tag:
        description: 'Nhập Tag cho Image (vd: v2, v3, latest)'
        required: true
        default: 'latest'

jobs:
  build-and-push:
    runs-on: self-hosted # Chạy trên máy WSL của bạn
    
    steps:
    - name: 📥 Checkout code
      uses: actions/checkout@v3

    - name: 🔐 Login to Harbor
      run: |
        echo "${{ secrets.HARBOR_PASSWORD }}" | docker login 172.31.87.182:80 -u "${{ secrets.HARBOR_USERNAME }}" --password-stdin

    - name: 🔨 Build Model Service Image
      run: |
        echo "Đang build Model Service với tag: ${{ github.event.inputs.version_tag }}"
        # Lưu ý: Thay ./model bằng tên thư mục chứa Dockerfile của Model Service nếu khác
        docker build -t 172.31.87.182:80/spotify-mlops/model-service:${{ github.event.inputs.version_tag }} ./model

    - name: 🚀 Push to Harbor
      run: |
        echo "Đang đẩy Image lên Harbor..."
        docker push 172.31.87.182:80/spotify-mlops/model-service:${{ github.event.inputs.version_tag }}
