name: Manual Deploy Production Model

on:
  workflow_dispatch: # Cho phép nhấn nút trên giao diện GitHub

jobs:
  deploy-model:
    runs-on: self-hosted
    steps:
      - name: Refresh Model Service
        run: |
          echo "🔄 Đang ra lệnh cho model-service kéo model Production mới nhất từ MLflow (EC2)..."
          
          # Lệnh này sẽ khởi động lại Pod của model-service. 
          # Khi khởi động lại, code app.py sẽ tự chạy lệnh mlflow.sklearn.load_model()
          # và lấy đúng bản model bạn vừa gắn nhãn Production trên EC2.
          
          kubectl rollout restart deployment model-service -n mlops-sentiment
          
          echo "⏳ Chờ Pod mới khởi động..."
          kubectl rollout status deployment model-service -n mlops-sentiment
          
          echo "✅ Model mới đã được triển khai thành công!"
