name: Manual Trigger Airflow Training

on:
  workflow_dispatch: # Cho phép nhấn nút "Run workflow" trên giao diện GitHub

jobs:
  trigger-airflow:
    runs-on: self-hosted
    steps:
      - name: Trigger Airflow DAG
        run: |
          echo "🚀 Kích hoạt Airflow Training Pipeline thủ công..."
          curl -X POST "http://localhost:31190/api/v1/dags/spotify_sentiment_train_k3s_native/dagRuns" \
          -H "Content-Type: application/json" \
          --user "admin:admin" \
          -d '{"conf": {}}'
