name: Trigger Local Airflow on Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  trigger-airflow:
    runs-on: self-hosted

    steps:
      - name: Kích hoạt DAG trực tiếp qua Kubernetes CLI
        run: |
          echo "🚀 Bắn tín hiệu thẳng vào Pod Scheduler của Airflow..."
          
          # Dùng kubectl exec để chui vào pod và gõ lệnh trigger
          kubectl exec -i deployment/airflow-scheduler -n airflow -- airflow dags trigger spotify_sentiment_train_k3s_native -c "{\"commit_sha\": \"${{ github.sha }}\", \"message\": \"Auto-triggered by Kubernetes CLI\"}"
          
          echo "✅ Đã kích hoạt thành công! Pod train sẽ tự động mọc lên."
