name: CI/CD Pipeline - Spotify MLOps

on:
  push:
    branches:
      - main
    paths:
      - 'model/train.py'               
      - 'model/dataset/**'              
      - 'dags/spotify_training_dag.py'  
  workflow_dispatch:

jobs:
  deploy-and-train:
    runs-on: self-hosted

    steps:
      - name: Checkout code từ GitHub về máy Runner
        uses: actions/checkout@v4

      - name: Nạp file DAG vào ổ cứng K8s (Deploy)
        run: |
          echo "Bơm file spotify_training_dag.py vào thẳng ổ cứng chung PVC..."
          kubectl cp dags/spotify_training_dag.py airflow/airflow-scheduler-0:/opt/airflow/dags/
          
          echo " Airflow Processor quét và cập nhật code mới..."
          sleep 45

      - name:  Pod Train Model trên K8s (Trigger)
        run: |
          echo "Trigger DAG..."
          # Bắn lệnh thẳng vào tên mới của Giám đốc (airflow-scheduler-0)
          kubectl exec -i airflow-scheduler-0 -n airflow -- airflow dags trigger spotify_sentiment_train_k3s_native -c "{\"commit_sha\": \"${{ github.sha }}\", \"message\": \"Auto-deployed and triggered by CI\"}"
          echo "Đã ra lệnh huấn luyện thành công!"
